sonar.projectKey=sharedrive
sonar.projectName=Sharedrive
sonar.projectVersion=1.2.6
sonar.host.url=http://10.10.80.6:9000
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=backend/**/*_test.go,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=backend/bin/**,backend/vendor/**,frontend/dist/**,frontend/node_modules/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/changelog.generated.ts,frontend/src/routeTree.gen.ts,**/*.gen.go
sonar.coverage.exclusions=backend/cmd/**,backend/internal/embed/**,frontend/src/changelog.generated.ts,frontend/src/routeTree.gen.ts