root = "/src"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["go"]
  kill_delay = "0.5s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root_change = true

[log]
  time = false

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"
  main = "magenta"

[misc]
  clean_on_exit = true
