// Package embed provides the embedded frontend distribution files.
// The actual dist/ directory is generated by the frontend build step
// and copied into this location before the Go binary is compiled.
package embed

import "embed"

//go:embed dist
var DistFS embed.FS
