import React from 'react'
import ReactDOM from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'

import { AuthProvider } from '@/lib/auth-context'
import { I18nProvider } from '@/lib/i18n'
import { initTheme } from '@/lib/theme'
import { routeTree } from './routeTree.gen' // generated by TanStack Router Vite plugin

import '@/index.css'

interface PwaIdentity {
  title: string
  shortTitle: string
  description: string
  manifest: string
  appleIcon: string
}

const sharedriveIdentity: PwaIdentity = {
  title: 'Sharedrive',
  shortTitle: 'Sharedrive',
  description: 'Sharedrive — self-hosted private file drive',
  manifest: '/site.webmanifest',
  appleIcon: '/apple-touch-icon.png',
}

function pwaIdentity(pathname: string): PwaIdentity {
  if (pathname === '/notes' || pathname.startsWith('/notes/')) {
    return { title: 'Sharedrive Noter', shortTitle: 'Noter', description: 'Noter og huskelister i Sharedrive', manifest: '/notes.webmanifest', appleIcon: '/notes-icon-192.png' }
  }
  if (pathname === '/rooms' || pathname.startsWith('/rooms/')) {
    return { title: 'Sharedrive Rooms', shortTitle: 'Rooms', description: 'Samtaler og samarbejdsrum i Sharedrive', manifest: '/rooms.webmanifest', appleIcon: '/rooms-icon-192.png' }
  }
  return sharedriveIdentity
}

function syncPwaIdentity(pathname: string) {
  const identity = pwaIdentity(pathname)
  document.querySelector<HTMLLinkElement>('#app-manifest')?.setAttribute('href', identity.manifest)
  document.title = identity.title
  document.querySelector<HTMLMetaElement>('meta[name="description"]')?.setAttribute('content', identity.description)
  document.querySelector<HTMLMetaElement>('meta[name="apple-mobile-web-app-title"]')?.setAttribute('content', identity.shortTitle)
  document.querySelector<HTMLLinkElement>('link[rel="apple-touch-icon"]')?.setAttribute('href', identity.appleIcon)
}

syncPwaIdentity(window.location.pathname)

// Apply theme before first paint to prevent FOUC
initTheme()

// Register service worker for PWA support (app-shell caching, share target)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js', { updateViaCache: 'none' })
      .then(registration => registration.update())
      .catch((err) => {
        console.warn('SW registration failed:', err)
      })
  })
}

// Capture the install prompt so the ShareTargetHint can trigger it
window.addEventListener('beforeinstallprompt', (e) => {
  e.preventDefault()
  ;(window as Window & { __pwaInstallPrompt?: typeof e }).__pwaInstallPrompt = e
  window.dispatchEvent(new Event('pwa-install-available'))
})

window.addEventListener('appinstalled', () => {
  delete (window as Window & { __pwaInstallPrompt?: Event }).__pwaInstallPrompt
  window.dispatchEvent(new Event('pwa-install-changed'))
})

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 30_000,
      retry: (failureCount, error) => {
        // Don't retry auth errors
        if (error instanceof Error && 'status' in error) {
          const status = (error as { status: number }).status
          if (status === 401 || status === 403) return false
        }
        return failureCount < 2
      },
    },
  },
})

const router = createRouter({
  routeTree,
  context: { queryClient },
})

router.subscribe('onResolved', () => syncPwaIdentity(router.state.location.pathname))

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <I18nProvider>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <RouterProvider router={router} />
        </AuthProvider>
      </QueryClientProvider>
    </I18nProvider>
  </React.StrictMode>,
)
