/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedIndexRouteImport } from './routes/shared.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password.index'
import { Route as AcceptInviteIndexRouteImport } from './routes/accept-invite.index'
import { Route as LoginTotpRouteImport } from './routes/login.totp'
import { Route as AuthTrashIndexRouteImport } from './routes/_auth.trash.index'
import { Route as AuthSharesIndexRouteImport } from './routes/_auth.shares.index'
import { Route as AuthSharedBrowseIndexRouteImport } from './routes/_auth.shared-browse.index'
import { Route as AuthRecentIndexRouteImport } from './routes/_auth.recent.index'
import { Route as AuthFilesIndexRouteImport } from './routes/_auth.files.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth.admin.users.index'
import { Route as AuthAdminTagsIndexRouteImport } from './routes/_auth.admin.tags.index'
import { Route as AuthAdminSettingsIndexRouteImport } from './routes/_auth.admin.settings.index'
import { Route as AuthAdminGroupsIndexRouteImport } from './routes/_auth.admin.groups.index'
import { Route as AuthAdminBlockedIpsIndexRouteImport } from './routes/_auth.admin.blocked-ips.index'
import { Route as AuthAdminBackupIndexRouteImport } from './routes/_auth.admin.backup.index'
import { Route as AuthAdminAuditLogsIndexRouteImport } from './routes/_auth.admin.audit-logs.index'
import { Route as AuthActivityIndexRouteImport } from './routes/_auth.activity.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteIndexRoute = AcceptInviteIndexRouteImport.update({
  id: '/accept-invite/',
  path: '/accept-invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTotpRoute = LoginTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => LoginRoute,
} as any)
const AuthTrashIndexRoute = AuthTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSharesIndexRoute = AuthSharesIndexRouteImport.update({
  id: '/shares/',
  path: '/shares/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSharedBrowseIndexRoute = AuthSharedBrowseIndexRouteImport.update({
  id: '/shared-browse/',
  path: '/shared-browse/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecentIndexRoute = AuthRecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesIndexRoute = AuthFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminTagsIndexRoute = AuthAdminTagsIndexRouteImport.update({
  id: '/admin/tags/',
  path: '/admin/tags/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminSettingsIndexRoute = AuthAdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminGroupsIndexRoute = AuthAdminGroupsIndexRouteImport.update({
  id: '/admin/groups/',
  path: '/admin/groups/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminBlockedIpsIndexRoute =
  AuthAdminBlockedIpsIndexRouteImport.update({
    id: '/admin/blocked-ips/',
    path: '/admin/blocked-ips/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdminBackupIndexRoute = AuthAdminBackupIndexRouteImport.update({
  id: '/admin/backup/',
  path: '/admin/backup/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAuditLogsIndexRoute = AuthAdminAuditLogsIndexRouteImport.update({
  id: '/admin/audit-logs/',
  path: '/admin/audit-logs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivityIndexRoute = AuthActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/login/totp': typeof LoginTotpRoute
  '/accept-invite/': typeof AcceptInviteIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/files/': typeof AuthFilesIndexRoute
  '/recent/': typeof AuthRecentIndexRoute
  '/shared-browse/': typeof AuthSharedBrowseIndexRoute
  '/shares/': typeof AuthSharesIndexRoute
  '/trash/': typeof AuthTrashIndexRoute
  '/admin/audit-logs/': typeof AuthAdminAuditLogsIndexRoute
  '/admin/backup/': typeof AuthAdminBackupIndexRoute
  '/admin/blocked-ips/': typeof AuthAdminBlockedIpsIndexRoute
  '/admin/groups/': typeof AuthAdminGroupsIndexRoute
  '/admin/settings/': typeof AuthAdminSettingsIndexRoute
  '/admin/tags/': typeof AuthAdminTagsIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
  '/activity/': typeof AuthActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/login/totp': typeof LoginTotpRoute
  '/accept-invite': typeof AcceptInviteIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/setup': typeof SetupIndexRoute
  '/shared': typeof SharedIndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/files': typeof AuthFilesIndexRoute
  '/recent': typeof AuthRecentIndexRoute
  '/shared-browse': typeof AuthSharedBrowseIndexRoute
  '/shares': typeof AuthSharesIndexRoute
  '/trash': typeof AuthTrashIndexRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsIndexRoute
  '/admin/backup': typeof AuthAdminBackupIndexRoute
  '/admin/blocked-ips': typeof AuthAdminBlockedIpsIndexRoute
  '/admin/groups': typeof AuthAdminGroupsIndexRoute
  '/admin/settings': typeof AuthAdminSettingsIndexRoute
  '/admin/tags': typeof AuthAdminTagsIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/activity': typeof AuthActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/totp': typeof LoginTotpRoute
  '/accept-invite/': typeof AcceptInviteIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/files/': typeof AuthFilesIndexRoute
  '/_auth/recent/': typeof AuthRecentIndexRoute
  '/_auth/shared-browse/': typeof AuthSharedBrowseIndexRoute
  '/_auth/shares/': typeof AuthSharesIndexRoute
  '/_auth/trash/': typeof AuthTrashIndexRoute
  '/_auth/admin/audit-logs/': typeof AuthAdminAuditLogsIndexRoute
  '/_auth/admin/backup/': typeof AuthAdminBackupIndexRoute
  '/_auth/admin/blocked-ips/': typeof AuthAdminBlockedIpsIndexRoute
  '/_auth/admin/groups/': typeof AuthAdminGroupsIndexRoute
  '/_auth/admin/settings/': typeof AuthAdminSettingsIndexRoute
  '/_auth/admin/tags/': typeof AuthAdminTagsIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/activity/': typeof AuthActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login/totp'
    | '/accept-invite/'
    | '/reset-password/'
    | '/setup/'
    | '/shared/'
    | '/admin/'
    | '/files/'
    | '/recent/'
    | '/shared-browse/'
    | '/shares/'
    | '/trash/'
    | '/admin/audit-logs/'
    | '/admin/backup/'
    | '/admin/blocked-ips/'
    | '/admin/groups/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/users/'
    | '/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login/totp'
    | '/accept-invite'
    | '/reset-password'
    | '/setup'
    | '/shared'
    | '/admin'
    | '/files'
    | '/recent'
    | '/shared-browse'
    | '/shares'
    | '/trash'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/blocked-ips'
    | '/admin/groups'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/activity'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/login/totp'
    | '/accept-invite/'
    | '/reset-password/'
    | '/setup/'
    | '/shared/'
    | '/_auth/admin/'
    | '/_auth/files/'
    | '/_auth/recent/'
    | '/_auth/shared-browse/'
    | '/_auth/shares/'
    | '/_auth/trash/'
    | '/_auth/admin/audit-logs/'
    | '/_auth/admin/backup/'
    | '/_auth/admin/blocked-ips/'
    | '/_auth/admin/groups/'
    | '/_auth/admin/settings/'
    | '/_auth/admin/tags/'
    | '/_auth/admin/users/'
    | '/_auth/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  AcceptInviteIndexRoute: typeof AcceptInviteIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/': {
      id: '/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/': {
      id: '/accept-invite/'
      path: '/accept-invite'
      fullPath: '/accept-invite/'
      preLoaderRoute: typeof AcceptInviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/totp': {
      id: '/login/totp'
      path: '/totp'
      fullPath: '/login/totp'
      preLoaderRoute: typeof LoginTotpRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/trash/': {
      id: '/_auth/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AuthTrashIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shares/': {
      id: '/_auth/shares/'
      path: '/shares'
      fullPath: '/shares/'
      preLoaderRoute: typeof AuthSharesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/shared-browse/': {
      id: '/_auth/shared-browse/'
      path: '/shared-browse'
      fullPath: '/shared-browse/'
      preLoaderRoute: typeof AuthSharedBrowseIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recent/': {
      id: '/_auth/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof AuthRecentIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files/': {
      id: '/_auth/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthFilesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/tags/': {
      id: '/_auth/admin/tags/'
      path: '/admin/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AuthAdminTagsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/settings/': {
      id: '/_auth/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthAdminSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/groups/': {
      id: '/_auth/admin/groups/'
      path: '/admin/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthAdminGroupsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/blocked-ips/': {
      id: '/_auth/admin/blocked-ips/'
      path: '/admin/blocked-ips'
      fullPath: '/admin/blocked-ips/'
      preLoaderRoute: typeof AuthAdminBlockedIpsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/backup/': {
      id: '/_auth/admin/backup/'
      path: '/admin/backup'
      fullPath: '/admin/backup/'
      preLoaderRoute: typeof AuthAdminBackupIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/audit-logs/': {
      id: '/_auth/admin/audit-logs/'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AuthAdminAuditLogsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activity/': {
      id: '/_auth/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthActivityIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthFilesIndexRoute: typeof AuthFilesIndexRoute
  AuthRecentIndexRoute: typeof AuthRecentIndexRoute
  AuthSharedBrowseIndexRoute: typeof AuthSharedBrowseIndexRoute
  AuthSharesIndexRoute: typeof AuthSharesIndexRoute
  AuthTrashIndexRoute: typeof AuthTrashIndexRoute
  AuthAdminAuditLogsIndexRoute: typeof AuthAdminAuditLogsIndexRoute
  AuthAdminBackupIndexRoute: typeof AuthAdminBackupIndexRoute
  AuthAdminBlockedIpsIndexRoute: typeof AuthAdminBlockedIpsIndexRoute
  AuthAdminGroupsIndexRoute: typeof AuthAdminGroupsIndexRoute
  AuthAdminSettingsIndexRoute: typeof AuthAdminSettingsIndexRoute
  AuthAdminTagsIndexRoute: typeof AuthAdminTagsIndexRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
  AuthActivityIndexRoute: typeof AuthActivityIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthFilesIndexRoute: AuthFilesIndexRoute,
  AuthRecentIndexRoute: AuthRecentIndexRoute,
  AuthSharedBrowseIndexRoute: AuthSharedBrowseIndexRoute,
  AuthSharesIndexRoute: AuthSharesIndexRoute,
  AuthTrashIndexRoute: AuthTrashIndexRoute,
  AuthAdminAuditLogsIndexRoute: AuthAdminAuditLogsIndexRoute,
  AuthAdminBackupIndexRoute: AuthAdminBackupIndexRoute,
  AuthAdminBlockedIpsIndexRoute: AuthAdminBlockedIpsIndexRoute,
  AuthAdminGroupsIndexRoute: AuthAdminGroupsIndexRoute,
  AuthAdminSettingsIndexRoute: AuthAdminSettingsIndexRoute,
  AuthAdminTagsIndexRoute: AuthAdminTagsIndexRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
  AuthActivityIndexRoute: AuthActivityIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LoginRouteChildren {
  LoginTotpRoute: typeof LoginTotpRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginTotpRoute: LoginTotpRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  AcceptInviteIndexRoute: AcceptInviteIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  SharedIndexRoute: SharedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
