package db

import (
	"context"
	"crypto/rand"
	"embed"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"github.com/rs/zerolog/log"
	"github.com/yourname/privatedrive/internal/config"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// New creates a new pgxpool connection pool and verifies connectivity.
func New(ctx context.Context, cfg *config.Config) (*pgxpool.Pool, error) {
	poolCfg, err := pgxpool.ParseConfig(cfg.PostgresDSN())
	if err != nil {
		return nil, fmt.Errorf("parse postgres DSN: %w", err)
	}

	poolCfg.MaxConns = 25
	poolCfg.MinConns = 2
	poolCfg.MaxConnLifetime = 1 * time.Hour
	poolCfg.MaxConnIdleTime = 30 * time.Minute
	poolCfg.HealthCheckPeriod = 1 * time.Minute

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("create postgres pool: %w", err)
	}

	// Verify connection
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("postgres ping: %w", err)
	}

	log.Info().
		Str("host", cfg.PostgresHost).
		Int("port", cfg.PostgresPort).
		Str("db", cfg.PostgresDB).
		Msg("connected to PostgreSQL")

	return pool, nil
}

// RunMigrations applies all pending goose migrations embedded in the binary.
func RunMigrations(ctx context.Context, pool *pgxpool.Pool) error {
	db := stdlib.OpenDBFromPool(pool)
	defer db.Close()

	goose.SetBaseFS(migrationFS)

	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("goose set dialect: %w", err)
	}

	if err := goose.UpContext(ctx, db, "migrations"); err != nil {
		return fmt.Errorf("goose migrate up: %w", err)
	}

	log.Info().Msg("database migrations applied")
	return nil
}

// ResolveWrapKey returns the backup wrap key to use for encrypting buddy tokens.
// Priority:
//  1. BACKUP_WRAP_KEY env var (explicit admin config)
//  2. backup_wrap_key row in system_settings (auto-generated by migration)
//
// This allows buddy backup to work out-of-the-box without admin intervention.
func ResolveWrapKey(ctx context.Context, pool *pgxpool.Pool, envKey string) (string, error) {
	if envKey != "" {
		return envKey, nil
	}
	var key string
	err := pool.QueryRow(ctx,
		`SELECT value FROM system_settings WHERE key = 'backup_wrap_key'`,
	).Scan(&key)
	if err != nil {
		// Fallback: generate in-memory (not persisted — only happens if migration
		// somehow didn't run; will be different on restart but better than crash).
		log.Warn().Msg("backup_wrap_key not found in system_settings, generating ephemeral key")
		b := make([]byte, 32)
		if _, err2 := rand.Read(b); err2 != nil {
			return "", fmt.Errorf("generate fallback wrap key: %w", err2)
		}
		return hex.EncodeToString(b), nil
	}
	return key, nil
}
